version: '3'

services:
  nodejs:
    #fill out the configuration here
    networks:
      - app-network
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:10-alpine
    restart: unless-stopped
    container_name: cmsc389t-web-template
  
  #the nginx configuration is given below
  #the website will run on localhost:80 
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/htmldocker-compose up -d --force-recreate

      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      #fill out your absolute path to your folder here
      device: /Users/sadena/UMD Classes/Fall 2023/CMSC389T/cmsc389T-web-template
      o: bind

networks:
  app-network:
    driver: bridge 
